enum class GameErrorID{
    INVALIDINPUTEXCEPTION,
    FILENOTFOUNDEXCEPTION,
    INSUFFICIENTFUNDEXCEPTION,
    BUILDINGISFULLEXCEPTION,
    BUILDINGISEMPTYEXCEPTION,
    COLORSETNOTOWNEDEXCEPTION,
    NOACCESSTOPROPERTYEXCEPTION
};